### ISSUE TITLE
Which is the start project.

### ISSUE THREAD

**Issue by miteamuser** [instructure/instructure-android#14]
I am not able run the project. Please give us a good readme to start the project.

**Comment by vahidsotudeh** [comment]
Please give us a good readme to start the project at least for student app

**Comment by bootstraponline** [comment]
Here's how to build Student, Teacher, and Parent.

> ./gradle/gradlew -p candroid :candroid:assembleDevDebug
> ./gradle/gradlew -p teacher :app:assembleDevDebug
>./gradle/gradlew -p parent :app:assembleDevDebug

**Comment by vahidsotudeh** [comment]
could be able to change urls and add our school domain ?

**Comment by adrach** [comment]
Make sure to do the checkout with symlinks enabled (especially on Windows).
If you are using Android Studio, then just open the individual folders as projects and it will work out of the box.
If you want to change the hosted instance URL, you are welcome to change the region specified in constants `AIRWOLF_DOMAIN_AMERICA` and/or 'AIRWOLF_DOMAIN_LIST' but that would not help much because it is still expected that the mobile app is talking to the hosted instance by instructure.
If anyone found out how to connect to the open-source server, please share the information.

So far, it looks like a number of API endpoints for interacting with the mobile app are missing in the open-source "canvas-lms" codebase

**Comment by huangdengpan** [comment]
Hi my,
The plugin pspdfkit is a real problem.
I have already contacted the sales of Pspdfkit company, they gave me a surprise price, $10,000/year. o(╯□╰)o
How to disable it or replace it?

**Comment by bootstraponline** [comment]
I don't think there's a great PSPDFKit alternative. You'd have to modify the app code to work without it.

**Comment by huangdengpan** [comment]
@bootstraponline 
Thank you for giving us so greatful open-source code, could you please let us know how to disable pspdfkit ?I am not sure I found all the places with pspdfkit function.

**Comment by bootstraponline** [comment]
I'm not sure either, we've never removed it before. My recommendation is to start with a working build, then remove the dependency from gradle, and modify the code as necessary to make the app build again.

**Comment by bootstraponline** [comment]
> I saw that the android-app created a never-ending access_token. How we can create the access_token like yours?

I think you need special permission from the Canvas LMS team to get a non-expiring access token. If you make an issue on the [canvas lms repo](https://github.com/instructure/canvas-lms/issues) I'll see if I can get clarification next week.
