### ISSUE TITLE
Build under windows

### ISSUE THREAD

**Issue by h4ppysmile** [instructure/instructure-android#17]
Hello,
How can I make the project in windows. It seams symlinks breaks during git pull. How can I make it work?
What symlinks are necessary to make candroid?

Thanks

**Comment by bootstraponline** [comment]
No one on the team uses windows. I think Linux or macOS will be easier.

**Comment by StephenBrough** [comment]
Symlinks for all the projects were created on macOS, so they won't work on Windows. However, with some effort, I have been able to get our projects to build on Windows.

Gradle is symlinked out to the gradle folder in the root directory of the monorepo. If you only plan on building one project then you could just replace the gradle symlinks with actual files. Otherwise you'll have to recreate those symlinks in Windows. 

We also use a `buildSrc` module to manage our dependencies. Most projects have a symlink to the monorepo's root directory `buildSrc`. Again, either create the actual `buildSrc` module or recreate the symlink in Windows.

You'll also run into issues with `merge-private-data.gradle`, which uses a hardcoded path separator that is not compatible with Windows. On line 89, you'll want to change the `/` to a `\\`.

Like @bootstraponline said, all the devs are on MacOS so it would definitely be easier to use either macOS or Linux. We don't really support building on Windows.
